# Generated by Django 5.2 on 2025-06-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_major_degree_type_major_description_major_duration_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='minor_credits_earned',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='辅修已修学分'),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_students', to='departments.major', verbose_name='辅修专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='major_students', to='departments.major', verbose_name='主修专业'),
        ),
    ]
