# Generated by Django 5.2 on 2025-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宿舍信息'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(blank=True, help_text='18位身份证号，可选填', max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
