# Generated by Django 5.2 on 2025-06-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "学生"), ("TEACHER", "教师"), ("ADMIN", "管理员")],
                default="STUDENT",
                max_length=10,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="student",
            name="credits_earned",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=5, verbose_name="已修学分"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="degree_level",
            field=models.CharField(max_length=20, verbose_name="学位等级"),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="major_department_students",
                to="departments.department",
                verbose_name="主修院系",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="dormitory",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="宿舍"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女")], max_length=2, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="年级/入学年份"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="home_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="家庭地址"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id_card",
            field=models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="departments.major",
                verbose_name="专业",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="minor_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minor_department_students",
                to="departments.department",
                verbose_name="辅修院系",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="电话"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id_num",
            field=models.CharField(max_length=50, unique=True, verbose_name="学号"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="departments.department",
                verbose_name="所属院系",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, verbose_name="教师姓名"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id_num",
            field=models.CharField(max_length=50, unique=True, verbose_name="教师工号"),
        ),
    ]
