# Generated by Django 5.2 on 2025-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allow_null_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='credits_earned',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='主修已修学分'),
        ),
    ]
