# Generated by Django 4.2.21 on 2025-05-30 12:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="百分制分数，保留两位小数",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("100.0")),
                        ],
                        verbose_name="分数",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="根据分数自动计算的绩点",
                        max_digits=3,
                        null=True,
                        verbose_name="绩点",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="成绩首次录入系统的时间", verbose_name="录入时间"
                    ),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
            ],
            options={
                "verbose_name": "成绩",
                "verbose_name_plural": "成绩",
                "ordering": [
                    "student",
                    "teaching_assignment__semester",
                    "teaching_assignment__course__course_name",
                ],
            },
        ),
    ]
