# Generated by Django 5.2 on 2025-06-15 13:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0003_courseenrollment"),
        ("users", "0002_alter_customuser_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="百分制分数，保留两位小数",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("100.0")),
                        ],
                        verbose_name="分数",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="根据分数自动计算的绩点",
                        max_digits=3,
                        null=True,
                        verbose_name="绩点",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="成绩首次录入系统的时间",
                        verbose_name="录入时间",
                    ),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades_received",
                        to="users.student",
                        verbose_name="学生",
                    ),
                ),
                (
                    "teaching_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.teachingassignment",
                        verbose_name="授课安排",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩",
                "verbose_name_plural": "成绩",
                "ordering": [
                    "student",
                    "teaching_assignment__semester",
                    "teaching_assignment__course__course_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "teaching_assignment"),
                        name="unique_student_teaching_assignment_grade",
                    )
                ],
            },
        ),
    ]
