# Generated by Django 4.2.21 on 2025-05-30 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grades", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后修改人",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grades_received",
                to="users.student",
                verbose_name="学生",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="teaching_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.teachingassignment",
                verbose_name="授课安排",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("student", "teaching_assignment"),
                name="unique_student_teaching_assignment_grade",
            ),
        ),
    ]
