"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-nk^v8%yimhn5fjw9vv$bcy_ad3c2h#s!8diy1eea*zkcuq!8)5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",       
    "departments",
    "courses",
    "grades",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'your_student_db_name',  # <--- 修改: 你的数据库名称
        'USER': 'your_mysql_username',    # <--- 修改: 你的 MySQL 用户名
        'PASSWORD': 'your_mysql_password',# <--- 修改: 你的 MySQL 密码
        'HOST': 'localhost',              # <--- 修改: (通常是 'localhost' 或数据库服务器 IP)
        'PORT': '3306',                   # <--- 修改: (MySQL 默认端口)
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", # 推荐的 MySQL 设置
            'charset': 'utf8mb4', # 推荐使用 utf8mb4 以支持更广泛的字符集
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# <--- 添加: 指定自定义的用户模型 ---
# 假设你的 Student 模型类名为 Student，且位于 'users' 应用的 models.py 文件中
AUTH_USER_MODEL = 'users.Student'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us" # 默认为英文
LANGUAGE_CODE = "zh-hans"  # <--- 可选修改: 设置为简体中文

# TIME_ZONE = "UTC" # 默认为UTC
TIME_ZONE = "Asia/Shanghai" # <--- 可选修改: 设置为中国上海时区

USE_I18N = True

USE_TZ = True # 推荐保持为 True，Django 会在内部处理时区转换


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"