# Generated by Django 4.2.21 on 2025-05-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.teacher",
                verbose_name="授课教师",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                help_text="开设该课程的院系",
                on_delete=django.db.models.deletion.PROTECT,
                to="departments.department",
                verbose_name="开课院系",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("teacher", "course", "semester")},
        ),
    ]
