# Generated by Django 5.2 on 2025-06-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="选课时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "已选课"),
                            ("DROPPED", "已退课"),
                            ("COMPLETED", "已完成"),
                        ],
                        default="ENROLLED",
                        max_length=20,
                        verbose_name="选课状态",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to="users.student",
                        verbose_name="学生",
                    ),
                ),
                (
                    "teaching_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="courses.teachingassignment",
                        verbose_name="授课安排",
                    ),
                ),
            ],
            options={
                "verbose_name": "选课记录",
                "verbose_name_plural": "选课记录",
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "teaching_assignment")},
            },
        ),
    ]
