# Generated by Django 5.2 on 2025-06-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courseenrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseenrollment",
            name="teaching_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.teachingassignment",
                verbose_name="授课安排",
            ),
        ),
    ]
