# Generated by Django 5.2 on 2025-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='degree_type',
            field=models.CharField(choices=[('bachelor', '学士'), ('master', '硕士'), ('doctor', '博士'), ('all', '本硕博')], default='bachelor', help_text='该专业提供的学位类型', max_length=20, verbose_name='学位类型'),
        ),
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.TextField(blank=True, help_text='专业的详细描述和培养目标（可选）', max_length=500, null=True, verbose_name='专业描述'),
        ),
        migrations.AddField(
            model_name='major',
            name='duration',
            field=models.CharField(choices=[('2', '2年'), ('3', '3年'), ('4', '4年'), ('5', '5年'), ('6', '6年')], default='4', help_text='该专业的标准学制年限', max_length=10, verbose_name='学制'),
        ),
        migrations.AddField(
            model_name='major',
            name='major_code',
            field=models.CharField(blank=True, help_text='专业的唯一代码，例如：CS001, MATH002', max_length=20, null=True, unique=True, verbose_name='专业代码'),
        ),
    ]
